name: instagram_clone
description: An instagram clone app using Flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7
  cloud_firestore: ^4.14.0
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  image_picker: ^1.0.8
  photo_manager: ^3.1.1
  firebase_storage: ^11.6.0
  sqlite_wrapper: ^0.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/insta_logo.png
    - assets/images/fb_logo.png
    - assets/icons/camera_icon.png
    - assets/icons/tv_icon.png
    - assets/icons/message_icon.png
    - assets/images/default_avatar.png
    - assets/icons/comment_icon.png
    - assets/icons/like_icon.png
    - assets/icons/like_icon_focused.png
    - assets/icons/message_icon.png
    - assets/icons/save_icon.png
    - assets/icons/home_icon.png
    - assets/icons/home_icon_focused.png
    - assets/icons/new_post_icon.png
    - assets/icons/save_icon.png
    - assets/icons/search_icon.png
    - assets/icons/search_icon_focused.png
    - assets/icons/grid_icon.png
    - assets/icons/tag_icon.png

  fonts:
    - family: InstaSan
      fonts:
        - asset: assets/fonts/insta_san/Instagram-Sans-Bold.ttf
        - asset: assets/fonts/insta_san/Instagram-Sans-Headline.otf
        - asset: assets/fonts/insta_san/Instagram-Sans-Light.ttf
        - asset: assets/fonts/insta_san/Instagram-Sans-Medium.ttf
        - asset: assets/fonts/insta_san/Instagram-Sans.ttf